# Generated by Django 4.1.3 on 2022-11-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myslack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_workspace_admin',
            field=models.BooleanField(default=False),
        ),
    ]
