# Generated by Django 4.1.3 on 2022-12-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myslack', '0002_profile_is_workspace_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='channelmembership',
            options={'ordering': ['profile', 'channel']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='commentreaction',
            options={'ordering': ['reaction']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='threadreaction',
            options={'ordering': ['reaction']},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['name']},
        ),
    ]
