# Generated by Django 4.1.3 on 2022-12-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myslack', '0003_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myslack.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='myslack.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='myslack.channel'),
        ),
    ]
